deploy 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,38 +53,40 @@ jobs:
                     echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
                   fi
 
-            - name: Deploy Application and Handle Failure
-              run: |
-                  if ! docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.CONTAINER_PORT }}:3000 \
-                    -e CORS_ORIGIN="${{ env.CORS_ORIGIN }}" \
-                    -e KAKAO_REDIRECT_URI="${{ env.KAKAO_REDIRECT_URI }}" \
-                    -e DATABASE_URL="${{ env.DATABASE_URL }}" \
-                    -e KAKAO_REST_API_KEY="${{ secrets.KAKAO_REST_API_KEY }}" \
-                    -e NAVER_REDIRECT_URI="${{ env.NAVER_REDIRECT_URI }}" \
-                    -e NAVER_CLIENT_SECRET="${{ secrets.NAVER_CLIENT_SECRET }}" \
-                    -e NAVER_REST_API_ID="${{ secrets.NAVER_REST_API_ID }}" \
-                    -e SESSION_SECRET="${{ secrets.SESSION_SECRET }}" \
-                    -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
-                    -e ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}" \
-                    -e REFRESH_TOKEN_SECRET="${{ secrets.REFRESH_TOKEN_SECRET }}" \
-                    -e ACCESS_TOKEN_LIFE="${{ secrets.ACCESS_TOKEN_LIFE }}" \
-                    -e REFRESH_TOKEN_LIFE="${{ secrets.REFRESH_TOKEN_LIFE }}" \
-                    -e CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" \
-                    -e SENTRY_DSN="${{ env.SENTRY_DSN }}" \
-                    leticia0408/byeol_gom:${{ github.ref == 'refs/heads/dev' && 'latest-dev' || 'latest-prod' }}; then
-                    echo "Deployment failed, notifying Slack and attempting rollback."
-                    CURRENT_IMAGE=$(docker inspect --format='{{.Config.Image}}' ${{ env.CONTAINER_NAME }} || echo "")
-                    docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.CONTAINER_PORT }}:3000 $CURRENT_IMAGE
-                  else
-                    echo "Deployment successful."
-                  fi
-
-            - name: Send Slack Notification on Deployment Failure
-              if: failure() # Only run this step if the deployment step failed
-              uses: 8398a7/action-slack@v3
+            - name: Deploy to Remote Server
+              uses: appleboy/ssh-action@v0.1.6
               with:
-                  status: custom
-                  fields: repo,commit,author,action,eventName,ref,workflow
-                  text: '🚨 Deployment to ${GITHUB_REF} failed and rollback was initiated.'
-              env:
-                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+                  host: ${{ secrets.REMOTE_IP }}
+                  username: ${{ secrets.REMOTE_USER }}
+                  key: ${{ secrets.REMOTE_PRIVATE_KEY }}
+                  port: ${{ secrets.REMOTE_SSH_PORT }}
+                  script: |
+                      CURRENT_IMAGE=$(docker inspect --format='{{.Config.Image}}' ${{ env.CONTAINER_NAME }} || echo "")
+                      docker system prune -a -f --volumes
+                      echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
+                      docker pull leticia0408/byeol_gom:${{ github.ref == 'refs/heads/dev' && 'latest-dev' || 'latest-prod' }}
+                      docker stop ${{ env.CONTAINER_NAME }} || true
+                      docker rm ${{ env.CONTAINER_NAME }} || true
+                      if docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.CONTAINER_PORT }}:3000 \
+                        -e CORS_ORIGIN="${{ secrets.CORS_ORIGIN_DEV }}" \
+                        -e KAKAO_REDIRECT_URI="${{ secrets.DEV_KAKAO_REDIRECT_URI }}" \
+                        -e DATABASE_URL="${{ secrets.DEV_DATABASE_URL }}" \
+                        -e KAKAO_REST_API_KEY="${{ secrets.KAKAO_REST_API_KEY }}" \
+                        -e NAVER_REDIRECT_URI="${{ secrets.DEV_NAVER_REDIRECT_URI }}" \
+                        -e NAVER_CLIENT_SECRET="${{ secrets.NAVER_CLIENT_SECRET }}" \
+                        -e NAVER_REST_API_ID="${{ secrets.NAVER_REST_API_ID }}" \
+                        -e SESSION_SECRET="${{ secrets.SESSION_SECRET }}" \
+                        -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
+                        -e ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}" \
+                        -e REFRESH_TOKEN_SECRET="${{ secrets.REFRESH_TOKEN_SECRET }}" \
+                        -e ACCESS_TOKEN_LIFE="${{ secrets.ACCESS_TOKEN_LIFE }}" \
+                        -e REFRESH_TOKEN_LIFE="${{ secrets.REFRESH_TOKEN_LIFE }}" \
+                        -e CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" \
+                        -e SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
+                        leticia0408/byeol_gom:${{ github.ref == 'refs/heads/dev' && 'latest-dev' || 'latest-prod' }}; then
+                        echo "Deployment successful."
+                      else
+                        echo "Deployment failed, rolling back to previous image."
+                        docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.CONTAINER_PORT }}:3000 $CURRENT_IMAGE
+                        curl -X POST -H 'Content-type: application/json' --data '{"text":"🚨 Deployment to ${{ github.ref }} failed and rollback was initiated."}' ${{ secrets.SLACK_WEBHOOK_URL }}
+                      fi
